# Generated by Django 3.0.8 on 2021-07-23 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='glosy_procent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wpis',
            name='glosy_wszystkie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wpis',
            name='zrodla',
            field=models.CharField(default='Twoje źródła', max_length=5000),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
