# Generated by Django 3.0.8 on 2021-07-23 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0002_auto_20210723_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
