# Generated by Django 3.0.8 on 2021-07-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0005_auto_20210723_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='zrodla',
            field=models.TextField(),
        ),
    ]
