# Generated by Django 3.0.8 on 2021-07-24 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0007_recenzja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('source', models.TextField()),
                ('all_vote', models.IntegerField(default=0)),
                ('percent_vote', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=50)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('single_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wpisy.Entry')),
            ],
        ),
        migrations.DeleteModel(
            name='Recenzja',
        ),
        migrations.DeleteModel(
            name='wpis',
        ),
    ]
