# Generated by Django 3.0.8 on 2021-07-24 14:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0008_auto_20210724_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='all_vote',
            new_name='vote_ratio',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='percent_vote',
            new_name='vote_total',
        ),
        migrations.RemoveField(
            model_name='review',
            name='create',
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='wpisy.Tag'),
        ),
    ]
