# Generated by Django 3.0.8 on 2021-09-21 13:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0010_auto_20210724_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='vote_ratio',
            new_name='count_shares',
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
