# Generated by Django 3.0.8 on 2021-10-12 01:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0012_auto_20211003_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=ckeditor.fields.RichTextField(default='Domyślny opis', max_length=280),
        ),
        migrations.AddField(
            model_name='tag',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
