# Generated by Django 3.0.8 on 2021-11-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0013_auto_20211012_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='left_or_right',
            field=models.CharField(default='left', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(default='Domyślny opis', max_length=280),
        ),
    ]
