# Generated by Django 3.0.8 on 2021-11-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0014_auto_20211103_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='when',
            field=models.IntegerField(default=0),
        ),
    ]
