# Generated by Django 3.0.8 on 2021-11-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0016_auto_20211117_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpicture',
            name='title',
            field=models.CharField(default='Główny', max_length=200),
        ),
    ]
