# Generated by Django 3.0.8 on 2021-11-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0018_entry_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default='Jasiek', max_length=24),
        ),
    ]
